In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:

!dir

 El volumen de la unidad C es OS
 El n£mero de serie del volumen es: 7C08-4B63

 Directorio de C:\Users\jdesa

20/03/2019  07:33 p. m.    <DIR>          .
20/03/2019  07:33 p. m.    <DIR>          ..
28/01/2019  07:22 p. m.                37 .gitconfig
20/03/2019  07:33 p. m.    <DIR>          .ipynb_checkpoints
16/01/2019  07:26 p. m.    <DIR>          .ipython
23/01/2019  01:08 p. m.    <DIR>          .jupyter
09/02/2019  11:57 a. m.    <DIR>          .matplotlib
17/02/2019  06:05 p. m.    <DIR>          .Origin
17/02/2019  06:05 p. m.    <DIR>          .QtWebEngineProcess
09/02/2019  11:57 a. m.    <DIR>          .spyder-py3
23/01/2019  07:14 p. m.         1,861,069 Ciclos.ipynb
03/03/2019  07:21 p. m.    <DIR>          Documents
05/12/2018  07:24 p. m.    <DIR>          FoundryAnalytics
23/01/2019  08:23 p. m.             5,966 Funciones.ipynb
20/03/2019  07:26 p. m.    <DIR>          OneDrive
26/02/2019  05:33 p. m.           111,211 optimizacion.ipynb
20/03/2019  07:28 p. m.            10,066 osv_acumulado_2013-2019.xlsx
20/03/2019  07:33 p. m.                72 Pandas.ipynb
13/02/2019  08:15 p. m.            10,175 Programacion lineal.ipynb
26/02/2019  06:00 p. m.           143,964 Sistema masa resorte.ipynb
06/03/2019  07:31 p. m.            56,946 Sistemas amortiguados.ipynb
11/03/2019  07:50 p. m.            22,879 Sistemas no lineales.ipynb
23/01/2019  05:19 p. m.             3,008 Tarea Tuplas, Listas, Diccionarios.ipynb
26/02/2019  06:24 p. m.            14,642 Tortuga and Numpy.ipynb
16/01/2019  08:44 p. m.             4,549 Variables.ipynb
              13 archivos      2,244,584 bytes
              12 dirs  18,723,692,544 bytes libres

In [10]:
data= pd.read_excel("osv_acumulado_2013-2019.xlsx",skiprows=3,skipfooter=2)
data

,MES,Pruebas aplicadas,Conductores retenidos,Sanción económica,Total pruebas positivas,% positivas/a plicadas,Días con Operativo,Promedio diario positivas
0,Noviembre (15-30),6659,142,59,201,3.02%,10,20.10
1,Diciembre,12332,220,77,297,2.41%,16,18.56
2,Enero 2014,16944,258,110,368,2.17%,19,19.37
3,Febrero,15850,343,141,484,3.05%,16,30.25
4,Marzo,16123,380,214,594,3.68%,17,34.94
5,Abril,15714,284,145,429,2.73%,17,25.24
6,Mayo,14774,287,183,470,3.18%,18,26.11
7,Junio,12704,288,151,439,3.46%,16,27.44
8,Julio,15343,326,168,494,3.22%,20,24.70
9,Agosto,18762,401,230,631,3.36%,18,35.06
10,Septiembre,11699,264,162,426,3.64%,16,26.63
11,Octubre,16407,398,224,622,3.79%,19,32.74
12,Noviembre,16281,331,232,563,3.46%,16,35.19
13,Diciembre,19965,351,194,545,2.73%,16,34.06
14,2015 Enero,21567,402,231,633,2.94%,19,33.32
15,Febrero,15083,303,151,454,3.01%,16,28.38
16,Marzo,16620,334,196,530,3.19%,17,31.18
17,Abril,19087,397,256,653,3.42%,19,34.37
18,Mayo,17640,349,230,579,3.28%,18,32.17
19,Junio,17556,400,257,657,3.74%,15,43.80
20,Julio,21242,476,314,790,3.72%,19,41.58
21,Agosto,19570,424,303,727,3.71%,17,42.76
22,Septiembre,21064,477,297,774,3.67%,18,43.00
23,Octubre,21322,497,254,751,3.52%,18,41.72
24,Noviembre,21671,357,223,580,2.68%,16,36.25
25,Diciembre,43666,383,296,679,1.55%,27,25.15
26,2016 Enero,46442,300,198,498,1.07%,31,16.06
27,Febrero,36626,271,204,475,1.30%,29,16.38
28,Marzo,22999,302,240,542,2.36%,31,17.48
29,Abril,25739,355,226,581,2.26%,30,19.37
...,...,...,...,...,...,...,...,...
34,Septiembre,31385,501,328,829,2.64%,30,27.63
35,Octubre,31182,506,274,780,2.50%,31,25.16
36,Noviembre,30572,412,280,692,2.26%,30,23.07
37,Diciembre,63943,610,397,1007,1.57%,31,32.48
38,2017 Enero,53312,438,249,687,1.29%,31,22.16
39,Febrero,41110,370,241,611,1.49%,28,21.82
40,Marzo,39320,392,255,647,1.65%,31,20.87
41,Abril,35619,356,199,555,1.56%,30,18.50
42,Mayo,36959,372,228,600,1.62%,31,19.35
43,Junio,38384,388,234,622,1.62%,30,20.73
44,Julio,34879,323,204,527,1.51%,31,17.00
45,Agosto,43992,405,283,688,1.56%,31,22.19
46,Septiembre,35725,343,208,551,1.54%,30,18.37
47,Octubre,40166,384,254,638,1.59%,31,20.58
48,Noviembre,39380,325,198,523,1.33%,30,17.43
49,Diciembre,54153,249,171,420,0.78%,31,13.55
50,Enero 2018,46770,305,211,516,1.10%,31,16.65
51,Febrero,35659,362,193,555,1.56%,28,19.82
52,Marzo,37769,480,245,725,1.92%,31,23.39
53,Abril,39912,464,260,724,1.81%,30,24.13
54,Mayo,39019,481,295,776,1.99%,30,25.87
55,Junio,36684,480,298,778,2.12%,30,25.93
56,Julio,34049,498,360,858,2.52%,30,28.60
57,Agosto,35848,463,343,806,2.25%,31,26.00
58,Septiembre,31885,344,295,639,2.00%,30,21.30
59,Octubre,31063,427,299,726,2.34%,31,23.42
60,Noviembre,27560,405,227,632,2.29%,30,21.07
61,Diciembre,148410,864,513,1377,0.93%,31,44.42
62,Enero 2019,89032,407,216,623,0.70%,15,41.53
63,Febrero,151658,907,477,1384,0.91%,28,49.43

In [7]:
data.tail()

,MES,Pruebas aplicadas,Conductores retenidos,Sanción económica,Total pruebas positivas,% positivas/a plicadas,Días con Operativo,Promedio diario positivas
61,Diciembre,148410.0,864.0,513.0,1377.0,0.93%,31.0,44.42
62,Enero 2019,89032.0,407.0,216.0,623.0,0.70%,15.0,41.53
63,Febrero,151658.0,907.0,477.0,1384.0,0.91%,28.0,49.43
64,Acumulado,2113245.0,24840.0,15214.0,40054.0,1.90%,1590.0,25.19
65,Fuente: Ce.Co.Vi.,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
data.head()

,MES,Pruebas aplicadas,Conductores retenidos,Sanción económica,Total pruebas positivas,% positivas/a plicadas,Días con Operativo,Promedio diario positivas
0,Noviembre (15-30),6659,142,59,201,3.02%,10,20.10
1,Diciembre,12332,220,77,297,2.41%,16,18.56
2,Enero 2014,16944,258,110,368,2.17%,19,19.37
3,Febrero,15850,343,141,484,3.05%,16,30.25
4,Marzo,16123,380,214,594,3.68%,17,34.94

In [14]:
data["Pruebas aplicadas"]

0       6659
1      12332
2      16944
3      15850
4      16123
5      15714
6      14774
7      12704
8      15343
9      18762
10     11699
11     16407
12     16281
13     19965
14     21567
15     15083
16     16620
17     19087
18     17640
19     17556
20     21242
21     19570
22     21064
23     21322
24     21671
25     43666
26     46442
27     36626
28     22999
29     25739
       ...
34     31385
35     31182
36     30572
37     63943
38     53312
39     41110
40     39320
41     35619
42     36959
43     38384
44     34879
45     43992
46     35725
47     40166
48     39380
49     54153
50     46770
51     35659
52     37769
53     39912
54     39019
55     36684
56     34049
57     35848
58     31885
59     31063
60     27560
61    148410
62     89032
63    151658
Name: Pruebas aplicadas, Length: 64, dtype: int64

In [19]:
Pa=sum(data["Pruebas aplicadas"])
Pa

2113245

In [20]:
Cr=data["Conductores retenidos"].sum()
Cr

24840

In [23]:
Prob=Cr/Pa
Prob*100

1.1754434530780862

In [24]:
data.describe()

,Pruebas aplicadas,Conductores retenidos,Sanción económica,Total pruebas positivas,Días con Operativo,Promedio diario positivas
count,64.000000,64.000000,64.000000,64.00000,64.000000,64.000000
mean,33019.453125,388.125000,237.718750,625.84375,24.843750,26.464375
std,25537.965370,122.652367,77.747754,196.03751,6.735876,8.762802
min,6659.000000,142.000000,59.000000,201.00000,10.000000,13.200000
25%,17619.000000,323.750000,197.500000,520.50000,18.000000,19.707500
50%,29066.000000,376.000000,230.000000,616.50000,30.000000,24.925000
75%,38542.750000,429.750000,275.500000,708.25000,31.000000,32.545000
max,151658.000000,907.000000,513.000000,1384.00000,31.000000,49.430000